export const COUNTRY_CODES = [
  { code: 'USA', value: 1, name: 'United States' },
  { code: 'GBR', value: 44, name: 'United Kingdom' },
  { code: 'AUS', value: 61, name: 'Australia' },
  { code: 'GER', value: 49, name: 'Germany' },
  { code: 'FRA', value: 33, name: 'France' },
  { code: 'AFG', value: 98, name: 'Afghanistan' },
  { code: 'ALB', value: 355, name: 'Albania' },
  { code: 'ALG', value: 213, name: 'Algeria' },
  { code: 'AND', value: 376, name: 'Andorra' },
  { code: 'ANG', value: 244, name: 'Angola' },
  { code: 'ARG', value: 54, name: 'Argentina' },
  { code: 'ARM', value: 374, name: 'Armenia' },
  { code: 'ARU', value: 297, name: 'Aruba' },
  { code: 'BEL', value: 32, name: 'Belgium' },
  { code: 'BEN', value: 229, name: 'Benin' },
  { code: 'BER', value: 1_441, name: 'Bermuda' },
  { code: 'BHU', value: 975, name: 'Bhutan' },
  { code: 'BOL', value: 591, name: 'Bolivia' },
  { code: 'BIH', value: 387, name: 'Bosnia and Herzegovina' },
  { code: 'BOT', value: 267, name: 'Botswana' },
  { code: 'BRA', value: 55, name: 'Brazil' },
  { code: 'BRU', value: 673, name: 'Brunei' },
  { code: 'BUL', value: 359, name: 'Bulgaria' },
  { code: 'BUR', value: 226, name: 'Burkina Faso' },
  { code: 'CAM', value: 237, name: 'Cameroon' },
  { code: 'CAN', value: 1, name: 'Canada' },
  { code: 'CPV', value: 238, name: 'Cabo Verde' },
  { code: 'CAY', value: 1_345, name: 'Cayman Islands' },
  { code: 'CTA', value: 236, name: 'Central African Republic' },
  { code: 'CHA', value: 235, name: 'Chad' },
  { code: 'CHI', value: 56, name: 'Chile' },
  { code: 'CHN', value: 86, name: 'China' },
  { code: 'COL', value: 57, name: 'Colombia' },
  { code: 'COM', value: 269, name: 'Comoros' },
  { code: 'CGO', value: 242, name: 'Congo' },
  { code: 'COD', value: 243, name: 'Congo (DRC)' },
  { code: 'CRC', value: 506, name: 'Costa Rica' },
  { code: 'CRO', value: 385, name: 'Croatia' },
  { code: 'CUB', value: 53, name: 'Cuba' },
  { code: 'CYP', value: 357, name: 'Cyprus' },
  { code: 'CZE', value: 420, name: 'Czech Republic' },
  { code: 'DEN', value: 45, name: 'Denmark' },
  { code: 'DJI', value: 253, name: 'Djibouti' },
  { code: 'DMA', value: 1_767, name: 'Dominica' },
  { code: 'DOM', value: 1_809, name: 'Dominican Republic' },
  { code: 'ECU', value: 593, name: 'Ecuador' },
  { code: 'EGY', value: 20, name: 'Egypt' },
  { code: 'ESA', value: 503, name: 'El Salvador' },
  { code: 'ENG', value: 44, name: 'England' },
  { code: 'EQG', value: 240, name: 'Equatorial Guinea' },
  { code: 'ERI', value: 291, name: 'Eritrea' },
  { code: 'EST', value: 372, name: 'Estonia' },
  { code: 'ETH', value: 251, name: 'Ethiopia' },
  { code: 'FAR', value: 298, name: 'Falkland Islands' },
  { code: 'FIJ', value: 679, name: 'Fiji' },
  { code: 'FIN', value: 358, name: 'Finland' },
  { code: 'GAB', value: 241, name: 'Gabon' },
  { code: 'GAM', value: 220, name: 'Gambia' },
  { code: 'GEO', value: 995, name: 'Georgia' },
  { code: 'GER', value: 49, name: 'Germany' },
  { code: 'GHA', value: 233, name: 'Ghana' },
  { code: 'GRE', value: 30, name: 'Greece' },
  { code: 'GRN', value: 1_473, name: 'Grenada' },
  { code: 'GUA', value: 502, name: 'Guatemala' },
  { code: 'GUI', value: 224, name: 'Guinea' },
  { code: 'GUM', value: 1_671, name: 'Guam' },
  { code: 'GUY', value: 592, name: 'Guyana' },
  { code: 'HAI', value: 509, name: 'Haiti' },
  { code: 'HON', value: 504, name: 'Honduras' },
  { code: 'HKG', value: 852, name: 'Hong Kong' },
  { code: 'HUN', value: 36, name: 'Hungary' },
  { code: 'IND', value: 91, name: 'India' },
  { code: 'IDN', value: 62, name: 'Indonesia' },
  { code: 'IRN', value: 98, name: 'Iran' },
  { code: 'IRQ', value: 964, name: 'Iraq' },
  { code: 'IRL', value: 353, name: 'Ireland' },
  { code: 'ISR', value: 972, name: 'Israel' },
  { code: 'ITA', value: 39, name: 'Italy' },
  { code: 'JAM', value: 1_876, name: 'Jamaica' },
  { code: 'JPN', value: 81, name: 'Japan' },
  { code: 'JOR', value: 962, name: 'Jordan' },
  { code: 'KAZ', value: 7, name: 'Kazakhstan' },
  { code: 'KEN', value: 254, name: 'Kenya' },
  { code: 'KOR', value: 82, name: 'Korea' },
  { code: 'KUW', value: 965, name: 'Kuwait' },
  { code: 'KGZ', value: 996, name: 'Kyrgyzstan' },
  { code: 'LAO', value: 856, name: 'Laos' },
  { code: 'LAT', value: 371, name: 'Latvia' },
  { code: 'LBN', value: 961, name: 'Lebanon' },
  { code: 'LES', value: 266, name: 'Lesotho' },
  { code: 'LBR', value: 231, name: 'Liberia' },
  { code: 'LBY', value: 218, name: 'Libya' },
  { code: 'LIE', value: 423, name: 'Liechtenstein' },
  { code: 'LTU', value: 370, name: 'Lithuania' },
  { code: 'LUX', value: 352, name: 'Luxembourg' },
  { code: 'MAC', value: 853, name: 'Macao' },
  { code: 'MAD', value: 261, name: 'Madagascar' },
  { code: 'MAS', value: 60, name: 'Malaysia' },
  { code: 'MLI', value: 223, name: 'Mali' },
  { code: 'MLT', value: 356, name: 'Malta' },
  { code: 'MHL', value: 692, name: 'Marshall Islands' },
  { code: 'MTN', value: 222, name: 'Mauritania' },
  { code: 'MRI', value: 230, name: 'Mauritius' },
  { code: 'MEX', value: 52, name: 'Mexico' },
  { code: 'MDA', value: 373, name: 'Moldova' },
  { code: 'MON', value: 976, name: 'Monaco' },
  { code: 'MNE', value: 382, name: 'Montenegro' },
  { code: 'MAR', value: 212, name: 'Morocco' },
  { code: 'MOZ', value: 258, name: 'Mozambique' },
  { code: 'MYA', value: 95, name: 'Myanmar' },
  { code: 'NAM', value: 264, name: 'Namibia' },
  { code: 'NRU', value: 674, name: 'Nauru' },
  { code: 'NEP', value: 977, name: 'Nepal' },
  { code: 'NED', value: 31, name: 'Netherlands' },
  { code: 'NZL', value: 64, name: 'New Zealand' },
  { code: 'NCA', value: 505, name: 'Nicaragua' },
  { code: 'NIG', value: 234, name: 'Nigeria' },
  { code: 'NGR', value: 227, name: 'Niger' },
  { code: 'NIR', value: 44, name: 'Northern Ireland' },
  { code: 'MKD', value: 389, name: 'North Macedonia' },
  { code: 'NOR', value: 47, name: 'Norway' },
  { code: 'OMA', value: 968, name: 'Oman' },
  { code: 'PAK', value: 92, name: 'Pakistan' },
  { code: 'PLW', value: 680, name: 'Palau' },
  { code: 'PLE', value: 970, name: 'Palestine' },
  { code: 'PAN', value: 507, name: 'Panama' },
  { code: 'PNG', value: 675, name: 'Papua New Guinea' },
  { code: 'PAR', value: 595, name: 'Paraguay' },
  { code: 'PER', value: 51, name: 'Peru' },
  { code: 'PHI', value: 63, name: 'Philippines' },
  { code: 'POL', value: 48, name: 'Poland' },
  { code: 'POR', value: 351, name: 'Portugal' },
  { code: 'PUR', value: 1_787, name: 'Puerto Rico' },
  { code: 'QAT', value: 974, name: 'Qatar' },
  { code: 'ROU', value: 40, name: 'Romania' },
  { code: 'RUS', value: 7, name: 'Russia' },
  { code: 'RWA', value: 250, name: 'Rwanda' },
  { code: 'SAM', value: 685, name: 'Samoa' },
  { code: 'KSA', value: 966, name: 'Saudi Arabia' },
  { code: 'SEN', value: 221, name: 'Senegal' },
  { code: 'SRB', value: 381, name: 'Serbia' },
  { code: 'SEY', value: 248, name: 'Seychelles' },
  { code: 'SLE', value: 232, name: 'Sierra Leone' },
  { code: 'SIN', value: 65, name: 'Singapore' },
  { code: 'SVK', value: 421, name: 'Slovakia' },
  { code: 'SLO', value: 386, name: 'Slovenia' },
  { code: 'SOL', value: 677, name: 'Solomon Islands' },
  { code: 'SOM', value: 252, name: 'Somalia' },
  { code: 'RSA', value: 27, name: 'South Africa' },
  { code: 'ESP', value: 34, name: 'Spain' },
  { code: 'SRI', value: 94, name: 'Sri Lanka' },
  { code: 'SUD', value: 249, name: 'Sudan' },
  { code: 'SUR', value: 597, name: 'Suriname' },
  { code: 'SWZ', value: 268, name: 'Swaziland' },
  { code: 'SWE', value: 46, name: 'Sweden' },
  { code: 'SUI', value: 41, name: 'Switzerland' },
  { code: 'SYR', value: 963, name: 'Syria' },
  { code: 'TPE', value: 886, name: 'Taiwan' },
  { code: 'TJK', value: 992, name: 'Tajikistan' },
  { code: 'TAN', value: 255, name: 'Tanzania' },
  { code: 'THA', value: 66, name: 'Thailand' },
  { code: 'TLS', value: 670, name: 'Timor-Leste' },
  { code: 'TOG', value: 228, name: 'Togo' },
  { code: 'TUN', value: 216, name: 'Tunisia' },
  { code: 'TUR', value: 90, name: 'Turkey' },
  { code: 'TKM', value: 993, name: 'Turkmenistan' },
  { code: 'TUV', value: 688, name: 'Tuvalu' },
  { code: 'UGA', value: 256, name: 'Uganda' },
  { code: 'UKR', value: 380, name: 'Ukraine' },
  { code: 'UAE', value: 971, name: 'United Arab Emirates' },
  { code: 'URU', value: 598, name: 'Uruguay' },
  { code: 'UZB', value: 998, name: 'Uzbekistan' },
  { code: 'VAN', value: 678, name: 'Vanuatu' },
  { code: 'VEN', value: 58, name: 'Venezuela' },
  { code: 'VIE', value: 84, name: 'Vietnam' },
  { code: 'ISV', value: 1_340, name: 'Virgin Islands (US)' },
  { code: 'YEM', value: 967, name: 'Yemen' },
  { code: 'ZAM', value: 260, name: 'Zambia' },
  { code: 'ZIM', value: 263, name: 'Zimbabwe' },
];
